extends RefCounted
## GENERATED by railway-clang-simulator/tools/export-body-v2-godot.mjs.
## Approved mono PCM is unchanged; L/R copies route channels and pad future starts.
const MODEL_ID := "platform-body-v2"
const RATE := 48000
const KERNELS := 8
const KERNEL_SECONDS := 0.3413333333333333
const KERNEL_LEAD := 0.0213333
const PAD := 2.0
const LOOKAHEAD := 0.014
const MASTER := 0.65
const ROOT := "res://assets/sounds/body_v2/"
const LOOP_SECONDS := 8.0
const LOOP_STAGGER := 0.731
const REF_DISTANCE := 4.0
const ROLLOFF := 1.2
const MAX_DISTANCE := 600.0
const SOUND_SPEED := 343.0
const DOPPLER := 0.3
const DEFAULT_CLANG_BALANCE_DB := 0.0
const SOURCE_HASHES := {"impact-1.wav":"3cbe3cf73f052978eb282c133c8d861a168fa73f4d20b8d8987399c2d53c49cb","impact-3.wav":"35d099be7e8057114d0949cca4c2019632d802b0dcaaaa56ce5d253a2b84e04b","impact-5.wav":"396745f72b50df7edf0b4203c539c4d76f04f53ae49d5a229a21e225043c2736","impact-7.wav":"b5992a978acef0eb6c8f66e47e8df73fee016ce5f0caa82dbfb7c93098ea290c","rolling-bed.wav":"42683b3ad58e5a98537b8f11b8d80b62ad12fd93284b22f5d3d884e1a9c1bef2","impact-2.wav":"c0745f750e25ad89cc4ad3113c0203395debe4c36f825a7bdd9886bcae61c44c","impact-0.wav":"c8340d1c58790a63f627975d22db0aed1f2b7afd7027aab3146161c2d7931ca6","impact-4.wav":"6853d653cae2eafb1783ca1db950f3b5f888a60953efd7c78e702de52c84cfd2","impact-6.wav":"9ebe68fc1a29bfec24541d28aec33027390195d78ee6b5150a81787daa50e86d"}
