extends RefCounted
## GENERATED by railway-clang-simulator/tools/export-joint-video-godot.js.
## 14 pairs of isolated strikes from the approved synthetic TrainVideo.mp4 take.
## Original clip timing/speed is not used: actual wheel/joint positions schedule hits.
## This reference speed normalizes loudness only; the video's speed is unknown.
const MODEL_ID := "joint-video-contact-v1"
const SOURCE_SYNTH_SHA256 := "bfabf8112fe1c2facb26d32ed9cdb4ad35af521b17c005ee599b7d253a220c6a"
const RATE := 44100
const REFERENCE_SPEED := 60.0
const KERNEL_LEAD := 0.017414966
const KERNEL_SECONDS := 0.133514739
const VARIANT_COUNT := 14
const KERNELS := 28
const KERNEL_PATH := "res://assets/sounds/lab/joint_video_strike_%02d.wav"
const ROLLING_PATH := "res://assets/sounds/lab/joint_video_rolling.wav"
## Preserve the approved variants' pitch and natural first/second-wheel balance.
const CLANG_SEMITONES := 0.0
const DEFAULT_CLANG_BALANCE_DB := 0.0
const KERNEL_GAIN := 0.944417318
const WHEEL_GAIN := [1.0, 1.0]
const ROLLING_GAIN := 0.210746196
const NOISE_NEAR := 3.0
const NOISE_REF := 1.131272
const NEAR_DISTANCE := 3.0
## Strength variation is baked into the 14 pairs, so do not apply it twice.
const HITS := [[1.0], [1.0], [1.0], [1.0]]
