extends RefCounted
## GENERATED by railway-clang-simulator/tools/physical-export-godot.js — do not edit by hand.
## Physical axle-over-joint model fitted to the approved take: ICF rake over one joint at
## 66.01 km/h (ICF: 22.297 m coach,
## 14.783 m bogie centres, 2.896 m wheelbase).

const RATE := 44100
const REFERENCE_SPEED := 66.0060      # km/h
## Kernels start this long before the wheel actually hits the joint (seconds).
const KERNEL_LEAD := 0.017415
const KERNEL_SECONDS := 0.522449
## Multiply kernel / rolling playback by these to undo the 16-bit export normalisation.
const KERNEL_GAIN := 0.499186
## Per axle class: equalises each kernel's energy to the loudest (the take's trailing-bogie
## "clang"), so distance to the listener — not the take's microphone position — sets loudness.
const CLASS_GAIN := [3.4703, 3.9688, 1.0000, 2.3883]
const ROLLING_GAIN := 0.245139
## Rolling noise radiated per wheel: level = sqrt(sum 1/(1+(d/NOISE_NEAR)^2) / NOISE_REF).
const NOISE_NEAR := 3
const NOISE_REF := 1.131272
## Distance (m) of the take's microphone from the joint: nearer = full level.
const NEAR_DISTANCE := 3.0
## Per-hit loudness recorded for axle classes 0..3 (lead bogie 1/2, trail bogie 1/2).
const HITS := [[1.7392,1.849,0.3047,0.1071],[0.8335,0.8096,1.3569,2.2737],[1.0905,1.1224,0.7174,1.0697],[0.6169,0.1908,2.0791,1.1132]]
