extends RefCounted
## GENERATED by railway-clang-simulator/tools/physical-export-godot.js — do not edit by hand.
## Physical axle-over-joint model fitted to the approved take: ICF rake over one joint at
## 66.01 km/h (ICF: 22.297 m coach,
## 14.783 m bogie centres, 2.896 m wheelbase).

const RATE := 44100
const REFERENCE_SPEED := 66.0060      # km/h
## Kernels start this long before the wheel actually hits the joint (seconds).
const KERNEL_LEAD := 0.017415
const KERNEL_SECONDS := 0.653719
const KERNELS := 2
## Game voicing: the second axle is lower and louder; fitted profile stays intact.
const CLANG_SEMITONES := -4.0
const DEFAULT_CLANG_BALANCE_DB := 5.0
## Multiply kernel / rolling playback by these to undo the 16-bit export normalisation.
const KERNEL_GAIN := 0.444799
## Kernels: WHEEL 1 = first wheel of a bogie over the joint ("cling", brighter),
## WHEEL 2 = the second, right after it ("clang", heavier). These gains bring both to equal
## energy; the game applies its own clang/cling balance on top.
const WHEEL_GAIN := [1.0000, 1.7436]
const ROLLING_GAIN := 0.247825
## Rolling noise radiated per wheel: level = sqrt(sum 1/(1+(d/NOISE_NEAR)^2) / NOISE_REF).
const NOISE_NEAR := 3
const NOISE_REF := 1.131272
## Distance (m) of the take's microphone from the joint: nearer = full level.
const NEAR_DISTANCE := 3.0
## Per-hit loudness recorded for axle positions 0..3 (lead bogie wheel 1/2, trail bogie wheel 1/2),
## normalised to mean 1 per position (the take's per-position loudness is left out: perspective).
const HITS := [[1.0378,0.8299,0.9762,1.1561],[1.0057,0.954,1.076,0.9643],[1.0455,0.9902,0.9995,0.9648],[0.9938,0.7986,0.8665,1.3412]]
