"""Fit curve-squeal power statistics; emit a compact JS spectrum, never source samples.

Run analyze-squeal.py first to extract/inspect the benchmark. Fit and held-out
windows are explicit so later changes can be compared with this calibration.
"""
import os,sys,json,hashlib
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'.analysis-deps'))
os.environ.setdefault('MPLCONFIGDIR',str(ROOT/'analysis'/'mpl'))
import numpy as np
from scipy import signal,ndimage
from scipy.io import wavfile

TRAIN=[(6,14),(18,26),(57,61),(64,67),(98,102),(106,109),(135,139),(142,144)]
HOLDOUT=[(14,18),(61,64),(102,106),(139,142)]
BACKGROUND=[(32,38),(73,78),(151,169)]
BANDS=[(2450,2850),(3400,3950),(4350,5000),(5250,5900),(6200,7050)]
sr,raw=wavfile.read(ROOT/'analysis'/'squeal-reference-48k.wav')
x=signal.resample_poly(raw.astype(np.float64)/32768,1,2);sr//=2
def psd(windows):
 spectra=[]
 for start,end in windows:
  f,p=signal.welch(x[round(start*sr):round(end*sr)],sr,nperseg=32768,noverlap=16384)
  spectra.append(p)
 return f,np.array(spectra)
f,p=psd(TRAIN);_,background=psd(BACKGROUND);_,held=psd(HOLDOUT)
floor=np.median(background,axis=0)
reference=np.maximum(np.mean(p,axis=0)-floor,0)
smooth=ndimage.gaussian_filter1d(reference,4/(f[1]-f[0]))
def ramp(a,b,x):
 u=np.clip((x-a)/(b-a),0,1);return u*u*(3-2*u)
mask=ramp(2250,2450,f)*(1-ramp(7200,7600,f))
target=smooth*mask
step=6;freq=np.arange(0,12000+step,step);density=np.interp(freq,f,target)
area=np.trapezoid(density,freq);density/=area
peaks=[]
for lo,hi in BANDS:
 indices=np.flatnonzero((f>=lo)&(f<=hi));i=indices[np.argmax(smooth[indices])]
 peaks.append({'bandHz':[lo,hi],'peakHz':round(float(f[i]),2),'fraction':round(float(np.trapezoid(target[indices],f[indices])/area),6)})
envelopes=[]
sos=signal.butter(4,[2450,7050],btype='bandpass',fs=sr,output='sos')
for start,end in TRAIN:
 band=signal.sosfilt(sos,x[round(start*sr):round(end*sr)])
 env=np.sqrt(ndimage.uniform_filter1d(band*band,size=round(sr*.12)))
 env=env[round(sr*.3):-round(sr*.3)];envelopes.append(env/np.mean(env))
envelope=np.concatenate(envelopes)
metadata={
 'source':'SquealingTrain.mp4','sourceSha256':hashlib.sha256((ROOT.parent/'SquealingTrain.mp4').read_bytes()).hexdigest(),
 'sourceSampleRate':44100,'analysisSampleRate':sr,'trainWindowsSeconds':TRAIN,'holdoutWindowsSeconds':HOLDOUT,'backgroundWindowsSeconds':BACKGROUND,
 'method':'Mean Welch power minus median straight-section background; 4 Hz Gaussian smoothing; 2250–7600 Hz tapered band; new seeded random-phase periodic synthesis.',
 'scope':'Recorded onboard squeal-band spectrum, not an isolated wheel measurement or absolute SPL. Horn-like harmonic bursts excluded. Radius/speed not measured from video.',
 'densityStepHz':step,'measuredRms':round(float(np.sqrt(area)),8),'runtimeRms':.11,
 'envelopeCoefficientOfVariation':round(float(np.std(envelope)),4),'envelopeP10P90':[round(float(v),4) for v in np.percentile(envelope,[10,90])],
 'peaks':peaks,'phaseCopied':False,'waveformCopied':False,
}
# Preserve absolute spectral data separately for an independent synthesis check.
np.savez(ROOT/'analysis'/'squeal-fit-target.npz',frequency=f,target=target,background=floor,heldout=np.maximum(held-floor,0)*mask)
profile={'source':metadata['source'],'stepHz':step,'rms':metadata['runtimeRms'],'peaks':peaks,'density':[float(f'{v:.7g}') for v in density]}
text='// Generated by scripts/fit-squeal-spectrum.py: power statistics only, no recorded samples or phase.\n'
text+='export const SQUEAL_PROFILE = '+json.dumps(profile,separators=(',',':'))+';\n'
(ROOT/'public'/'squeal-profile.js').write_text(text,encoding='utf-8')
(ROOT/'public'/'squeal-fit.json').write_text(json.dumps(metadata,indent=2)+'\n',encoding='utf-8')
print(json.dumps({k:metadata[k] for k in ['measuredRms','runtimeRms','envelopeCoefficientOfVariation','envelopeP10P90','peaks']},indent=2))
